### ISSUE TITLE
video codec not supported

### ISSUE THREAD

**Issue by FidanBacaj** [duanhong169/Camera#2]
When I make a video with this library ( `com.github.duanhong169:camera:1.0.3` ) and when i click to play this video ,video not played just voice and writes "**video codec not supported**"

Can you help me for this problem  how to fix ?

**Comment by duanhong169** [comment]
Hi @FidanBacaj :

You can find the default video recorder config [here](https://github.com/duanhong169/Camera/blob/master/camera/src/main/java/top/defaults/camera/Camera2Photographer.java#L851-L870):

https://github.com/duanhong169/Camera/blob/6077681d059eb5f8f01ffbf373ebc35ed01e3def/camera/src/main/java/top/defaults/camera/Camera2Photographer.java#L851-L870

As you can see, the default video format & codec is:

```java
mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264);
```

So the problem is that the video player your phone provided may not support the `H264` codec, so it cannot play the video for you.

There are two ways to solve the issue:

1. Install a video player which support the `H264` codec.
2. Configure the video codec by passing in a `Photographer.MediaRecorderConfigurator` object when you calling `Photographer.startRecording(MediaRecorderConfigurator configurator)`, and set another video codec which your currently using video player supported:

```java
mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H263); // for example
```

You may find these two classes helpful:

* [MediaRecorder.OutputFormat](https://developer.android.com/reference/android/media/MediaRecorder.OutputFormat)
* [MediaRecorder.VideoEncoder](https://developer.android.com/reference/android/media/MediaRecorder.VideoEncoder)

**Comment by FidanBacaj** [comment]
Thank you @duanhong169  for quick answer !

**Comment by duanhong169** [comment]
@FidanBacaj Always welcome!
BTW, it will be fine if you give this project a star, then more people can reach here! 😊
